name: Build ImmortalWrt Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Free Disk Space (Ubuntu Runner)
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt-get clean

      - name: Initialize Build Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison gawk gettext ccache python3-setuptools \
            g++ gcc-multilib libncurses5-dev libssl-dev python3-pyelftools git \
            rsync unzip zlib1g-dev lib32gcc-s1 libc6-dev-i386 file

      - name: Clone ImmortalWrt Source & Add Extra Feeds
        run: |
          git clone -b master --single-branch https://github.com/immortalwrt/immortalwrt.git openwrt
          cd openwrt
          
          # 追加第三方常用软件源 (确保 PassWall / OpenClash 软件齐全)
          echo "src-git passwall https://github.com/xiaorouji/openwrt-passwall.git;main" >> feeds.conf.default
          echo "src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall-packages.git;main" >> feeds.conf.default
          
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Load Custom Configuration & Files
        run: |
          [ -e rax3000m.config ] && cp rax3000m.config openwrt/.config
          [ -d files ] && cp -r files openwrt/files
          # 加上这行即可自动赋予执行权限：
          chmod -R +x openwrt/files/etc/uci-defaults/

      - name: Download Package Source
        run: |
          cd openwrt
          make defconfig
          make download -j8

      - name: Compile Firmware
        run: |
          cd openwrt
          make -j$(nproc) V=s

      - name: Upload Firmware Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ImmortalWrt_RAX3000M
          path: openwrt/bin/targets/mediatek/filogic/*cmcc_rax3000m*
